In [39]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mutual_info_score
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression
import math

In [40]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv")

In [41]:
df

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1
...,...,...,...,...,...,...,...,...,...
4995,organic_search,education,employed,asia,45834.0,2,2,0.37,1
4996,NaN,technology,employed,north_america,84831.0,2,5,0.51,0
4997,organic_search,finance,employed,asia,53636.0,4,6,0.75,1
4998,referral,technology,employed,africa,69430.0,4,8,0.79,1
4999,referral,technology,employed,europe,81355.0,6,11,0.99,1

In [42]:
df.isna().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   lead_source               4852 non-null   str
 1   industry                  4760 non-null   str
 2   employment_status         4806 non-null   str
 3   location                  4792 non-null   str
 4   annual_income             4631 non-null   float64
 5   number_of_courses_viewed  5000 non-null   int64
 6   interaction_count         5000 non-null   int64
 7   lead_score                4965 non-null   float64
 8   converted                 5000 non-null   int64
dtypes: float64(2), int64(3), str(4)
memory usage: 351.7 KB

In [44]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
lead_source,4852,5,organic_search,1251,NaN,NaN,NaN,NaN,NaN,NaN,NaN
industry,4760,6,technology,1173,NaN,NaN,NaN,NaN,NaN,NaN,NaN
employment_status,4806,4,employed,2633,NaN,NaN,NaN,NaN,NaN,NaN,NaN
location,4792,5,north_america,1371,NaN,NaN,NaN,NaN,NaN,NaN,NaN
annual_income,4631.0,NaN,NaN,NaN,54533.212049,21245.66171,12000.0,40458.5,55051.0,71252.5,109886.0
number_of_courses_viewed,5000.0,NaN,NaN,NaN,2.0894,1.188987,0.0,1.0,2.0,3.0,6.0
interaction_count,5000.0,NaN,NaN,NaN,4.4726,2.435906,0.0,3.0,4.0,6.0,13.0
lead_score,4965.0,NaN,NaN,NaN,0.494767,0.199431,0.01,0.36,0.49,0.63,0.99
converted,5000.0,NaN,NaN,NaN,0.5766,0.494147,0.0,0.0,1.0,1.0,1.0

In [45]:
df["interaction_count"].nunique()

14

In [46]:
categorical_features = ["lead_source", "industry", "employment_status", "location"]
numerical_features = ["annual_income", "number_of_courses_viewed", "interaction_count", "lead_score"]

In [47]:
df[categorical_features] = df[categorical_features].fillna('NA')

In [48]:
df[[col for col in df.columns if col not in categorical_features]] = df[[col for col in df.columns if col not in categorical_features]].fillna(0)

In [49]:
df

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NA,0.0,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1
...,...,...,...,...,...,...,...,...,...
4995,organic_search,education,employed,asia,45834.0,2,2,0.37,1
4996,NA,technology,employed,north_america,84831.0,2,5,0.51,0
4997,organic_search,finance,employed,asia,53636.0,4,6,0.75,1
4998,referral,technology,employed,africa,69430.0,4,8,0.79,1
4999,referral,technology,employed,europe,81355.0,6,11,0.99,1

In [50]:
df["industry"].mode()

0    technology
Name: industry, dtype: str

In [51]:
numerical_features

['annual_income',
 'number_of_courses_viewed',
 'interaction_count',
 'lead_score']

In [52]:
(df[numerical_features].corr().values - np.eye(4)).max()

np.float64(0.9157457980418697)

In [53]:
df[numerical_features].corr()

,annual_income,number_of_courses_viewed,interaction_count,lead_score
annual_income,1.000000,0.161300,0.122842,0.229496
number_of_courses_viewed,0.161300,1.000000,0.721609,0.757204
interaction_count,0.122842,0.721609,1.000000,0.915746
lead_score,0.229496,0.757204,0.915746,1.000000

In [54]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(
    df_full_train, test_size=0.25, random_state=42
)

In [55]:
len(df_train), len(df_val), len(df_test)

(3000, 1000, 1000)

In [56]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [57]:
y_train = df_train.converted.values
y_val = df_val.converted.values
y_test = df_test.converted.values

In [58]:
del df_train['converted']
del df_val['converted']
del df_test['converted']

In [59]:
def mutual_info_converted_score(series):
    return mutual_info_score(series, df_full_train.converted)

In [60]:
mi = df_full_train[categorical_features].apply(mutual_info_converted_score)
mi.sort_values(ascending=False)

lead_source          0.034761
employment_status    0.020313
industry             0.002898
location             0.001050
dtype: float64

In [61]:
dv = DictVectorizer(sparse = False)
train_dict = df_train[categorical_features + numerical_features].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

In [62]:
X_train.shape

(3000, 28)

In [63]:
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [64]:
val_dict = df_val[categorical_features + numerical_features].to_dict(orient="records")
X_val = dv.transform(val_dict)

y_pred = model.predict(X_val)

In [65]:
round(float((y_pred == y_val).mean()), 2)

0.65

In [66]:
(y_pred == y_val).mean()

np.float64(0.645)

In [67]:
all_features = categorical_features + numerical_features
baseline_accuracy = (y_pred == y_val).mean()

feature_results = []

for feature in all_features:
    selected_features = [f for f in all_features if f != feature]

    dv_new = DictVectorizer(sparse=False)

    train_dict_new = df_train[selected_features].to_dict(orient="records")
    X_train_new = dv_new.fit_transform(train_dict_new)

    model_new = LogisticRegression(solver="liblinear", C=1.0, max_iter=1000, random_state=42)
    model_new.fit(X_train_new, y_train)

    val_dict_new = df_val[selected_features].to_dict(orient="records")
    X_val_new = dv_new.transform(val_dict_new)

    y_pred_new = model_new.predict(X_val_new)
    accuracy_new = (y_pred_new == y_val).mean()

    feature_results.append(
        (feature, float(accuracy_new), float(abs(baseline_accuracy - accuracy_new)))
    )

In [68]:
feature_results

[('lead_source', 0.642, 0.0030000000000000027),
 ('industry', 0.645, 0.0),
 ('employment_status', 0.645, 0.0),
 ('location', 0.645, 0.0),
 ('annual_income', 0.724, 0.07899999999999996),
 ('number_of_courses_viewed', 0.643, 0.0020000000000000018),
 ('interaction_count', 0.601, 0.04400000000000004),
 ('lead_score', 0.644, 0.0010000000000000009)]

In [74]:
ans = []

for C in [0.000001, 0.00001, 0.0001, 0.001]:
    X_train = dv.transform(train_dict)

    model = LogisticRegression(solver='liblinear', C=C, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)

    val_dict = df_val[categorical_features + numerical_features].to_dict(orient="records")
    X_val = dv.transform(val_dict)
    
    y_pred = model.predict(X_val)

    ans.append((round(float((y_pred==y_val).mean()), 3), C))

In [75]:
ans.sort()

In [76]:
ans

[(0.598, 1e-06), (0.598, 1e-05), (0.613, 0.0001), (0.645, 0.001)]